config/routes.rb
Rails.application.routes.draw do
  
  get 'availabilities/search_availability', to: 'availabilities#search_availability'
  get 'availabilities/result_search', to: 'availabilities#result_search'

  get 'turns/search_turn', to: 'turns#search_turn'
  get 'turns/result_search', to: 'turns#result_search'

  resources :availability_engineers
  resources :turns
  resources :availabilities
  resources :calendars
  resources :services
  resources :engineers
  resources :schedules
  root 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

end

app/models/availability_engineer.rb
class AvailabilityEngineer < ApplicationRecord
  belongs_to :availability
  belongs_to :engineer
end

app/controllers/availability_engineers_controller.rb
class AvailabilityEngineersController < ApplicationController
  before_action :set_availability_engineer, only: %i[ show edit update destroy ]

  # GET /availability_engineers or /availability_engineers.json
  def index
    @availability_engineers = AvailabilityEngineer.all
  end

  # GET /availability_engineers/1 or /availability_engineers/1.json
  def show
  end

  # GET /availability_engineers/new
  def new
    @availability_engineer = AvailabilityEngineer.new
  end

  # GET /availability_engineers/1/edit
  def edit
  end

  # POST /availability_engineers or /availability_engineers.json
  def create
    @availability_engineer = AvailabilityEngineer.new(availability_engineer_params)

    respond_to do |format|
      if @availability_engineer.save
        format.html { redirect_to availability_engineer_url(@availability_engineer), notice: "Availability engineer was successfully created." }
        format.json { render :show, status: :created, location: @availability_engineer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @availability_engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availability_engineers/1 or /availability_engineers/1.json
  def update
    respond_to do |format|
      if @availability_engineer.update(availability_engineer_params)
        format.html { redirect_to availability_engineer_url(@availability_engineer), notice: "Availability engineer was successfully updated." }
        format.json { render :show, status: :ok, location: @availability_engineer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @availability_engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availability_engineers/1 or /availability_engineers/1.json
  def destroy
    @availability_engineer.destroy

    respond_to do |format|
      format.html { redirect_to availability_engineers_url, notice: "Availability engineer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability_engineer
      @availability_engineer = AvailabilityEngineer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def availability_engineer_params
      params.require(:availability_engineer).permit(:availability_id, :engineer_id)
    end
end

app/helpers/availability_engineers_helper.rb
module AvailabilityEngineersHelper
end

app/views/availability_engineers/_form.html.erb
<%= simple_form_for(@availability_engineer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :availability %>
    <%= f.association :engineer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/availability_engineers/edit.html.erb
<h1>Editing Availability Engineer</h1>

<%= render 'form', availability_engineer: @availability_engineer %>

<%= link_to 'Show', @availability_engineer %> |
<%= link_to 'Back', availability_engineers_path %>

app/views/availability_engineers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Availability Engineers</h1>

<table>
  <thead>
    <tr>
      <th>Availability</th>
      <th>Engineer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availability_engineers.each do |availability_engineer| %>
      <tr>
        <td><%= availability_engineer.availability_id %></td>
        <td><%= availability_engineer.engineer_id %></td>
        <td><%= link_to 'Show', availability_engineer %></td>
        <td><%= link_to 'Edit', edit_availability_engineer_path(availability_engineer) %></td>
        <td><%= link_to 'Destroy', availability_engineer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Availability Engineer', new_availability_engineer_path %>

app/views/availability_engineers/new.html.erb
<h1>New Availability Engineer</h1>

<%= render 'form', availability_engineer: @availability_engineer %>

<%= link_to 'Back', availability_engineers_path %>

app/views/availability_engineers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Availability:</strong>
  <%= @availability_engineer.availability_id %>
</p>

<p>
  <strong>Engineer:</strong>
  <%= @availability_engineer.engineer_id %>
</p>

<%= link_to 'Edit', edit_availability_engineer_path(@availability_engineer) %> |
<%= link_to 'Back', availability_engineers_path %>