config/routes.rb
Rails.application.routes.draw do
  
  get 'availabilities/search_availability', to: 'availabilities#search_availability'
  get 'availabilities/result_search', to: 'availabilities#result_search'

  get 'turns/search_turn', to: 'turns#search_turn'
  get 'turns/result_search', to: 'turns#result_search'

  resources :availability_engineers
  resources :turns
  resources :availabilities
  resources :calendars
  resources :services
  resources :engineers
  resources :schedules
  root 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :service
  belongs_to :engineer

  validates_uniqueness_of  :engineer_id, scope: [:service_id, :hs, :date]

  # Selecciono los turnos ocupados de un prestador en la fecha seleccionada.
  def self.turns_occupied(service, date_from, engineer)
    Availability.where('service_id = ? AND date = ? AND engineer_id = ? AND canceled = ?', service, date_from, engineer, "false").pluck(:hs)
  end

end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_turn, only: %i[ show edit update destroy ]

  # GET /turns or /turns.json
  def index
    @turns = Turn.all
  end

  # GET /turns/1 or /turns/1.json
  def show
  end

  # GET /turns/new
  def new
    #@turn = Turn.new
    @date_from = params[:date_from]
    @date_to = params[:date_to]
    @service = params[:service]
    @turns = Availability.where('service_id = ? AND date >= ? AND date <= ?', @service, @date_from, @date_to).order(date: :asc)

    @turns.each do |turn|
      turn_add = Turn.where('date = ? AND hs = ? AND service_id = ?', turn.date, turn.hs, turn.service_id)
      if turn_add.present?
      else
      repeat_turns = Availability.where('date = ? AND hs = ? AND service_id = ? AND engineer_id <> ?', turn.date, turn.hs, turn.service_id, turn.engineer_id)
      cant_turns_avai = AvailabilityEngineer.joins(:availability).where('date >= ? AND date <= ? AND service_id = ?', @date_from, @date_to, @service).distinct.count(:availability_id)
      #cant_turns_avai = Availability.select('date, hs, service_id').distinct.where('date >= ? AND date <= ? AND service_id = ?', @date_from, @date_to, @service)
      #cant_turns_avai = AvailabilityEngineer.select('id').distinct


      if repeat_turns.present?
        # selecciono el primer turno que se genero entre todos los engineers (el primero que lo asignó)
        first_turn_add = Availability.where('date = ? AND hs = ? AND service_id = ?', turn.date, turn.hs, turn.service_id).order(created_at: :asc).first
        # cantidad turnos asignados al engineer que viene iterando
        cant = Turn.where('date >= ? AND date <= ? AND service_id = ? AND engineer_id = ?',@date_from, @date_to, @service, turn.engineer_id).count
        cant_engineer = Turn.where('date >= ? AND date <= ? AND service_id = ?',@date_from, @date_to, @service).distinct.count(:engineer_id)
        limit_turns = cant_turns_avai / 3
        #ningun enginer puede trabajar mas de 18 turnos por semana (busco si hay segundo ingeniero con horarios disponibles para trabajar)
        if cant >= limit_turns
          second_turn_add = Availability.where('date = ? AND hs = ? AND service_id = ?', turn.date, turn.hs, turn.service_id).order(created_at: :asc).second
          # cantidad turnos asignados al engineer que viene iterando
          cant = Turn.where('date >= ? AND date <= ? AND service_id = ? AND engineer_id = ?',@date_from, @date_to, @service, second_turn_add.engineer_id).count
          # si el segundo ingeniero ya tiene asignado muchas horas busco un tercero
          if cant >= limit_turns
            third_turn_add = Availability.where('date = ? AND hs = ? AND service_id = ?', turn.date, turn.hs, turn.service_id).order(created_at: :asc).third
            # cantidad turnos asignados al engineer que viene iterando
            cant = Turn.where('date >= ? AND date <= ? AND service_id = ? AND engineer_id = ?',@date_from, @date_to, @service, third_turn_add.engineer_id).count
            # si el segundo ingeniero ya tiene asignado muchas horas busco un tercero
            if cant >= limit_turns
            else
              @turn = Turn.new(:date => third_turn_add.date, :hs => third_turn_add.hs, :canceled => false, :service_id => third_turn_add.service_id, :engineer_id => third_turn_add.engineer_id)
              #UserMailer.with(turn: @turn).turn_summary_email.deliver_now #if Rails.env.production?
              @turn.save!
            end

          else
            @turn = Turn.new(:date => second_turn_add.date, :hs => second_turn_add.hs, :canceled => false, :service_id => second_turn_add.service_id, :engineer_id => second_turn_add.engineer_id)
            #UserMailer.with(turn: @turn).turn_summary_email.deliver_now #if Rails.env.production?
            @turn.save!
          end
        else
          @turn = Turn.new(:date => first_turn_add.date, :hs => first_turn_add.hs, :canceled => false, :service_id => first_turn_add.service_id, :engineer_id => first_turn_add.engineer_id)
          #UserMailer.with(turn: @turn).turn_summary_email.deliver_now #if Rails.env.production?
          @turn.save!
        end

      else
        cant = Turn.where('date >= ? AND date <= ? AND service_id = ? AND engineer_id = ?',@date_from, @date_to, @service, turn.engineer_id).count
        limit_turns = cant_turns_avai / 3
        #ningun enginer puede trabajar mas de 18hs por semana
        if cant >= limit_turns
          
        else
          @turn = Turn.new(:date => turn.date, :hs => turn.hs, :canceled => false, :service_id => turn.service_id, :engineer_id => turn.engineer_id)
          #UserMailer.with(turn: @turn).turn_summary_email.deliver_now #if Rails.env.production?
          @turn.save!
        end
      end
      end
    end
    redirect_to turns_path
  end

  # GET /turns/1/edit
  def edit
  end

  # POST /turns or /turns.json
  def create
    @turn = Turn.new(turn_params)

    respond_to do |format|
      if @turn.save
        format.html { redirect_to turn_url(@turn), notice: "Turn was successfully created." }
        format.json { render :show, status: :created, location: @turn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turns/1 or /turns/1.json
  def update
    respond_to do |format|
      if @turn.update(turn_params)
        format.html { redirect_to turn_url(@turn), notice: "Turn was successfully updated." }
        format.json { render :show, status: :ok, location: @turn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turns/1 or /turns/1.json
  def destroy
    @turn.destroy

    respond_to do |format|
      format.html { redirect_to turns_url, notice: "Turn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search_turn
    @service = Service.all
  end

  def result_search
    @service = params[:service]
    @date_from = params[:date_from]
    @date_to = params[:date_to]
    @turns = Availability.where('service_id = ? AND date >= ? AND date <= ?', @service, @date_from, @date_to)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn
      @turn = Turn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turn_params
      params.require(:turn).permit(:date, :hs, :canceled, :service_id, :engineer_id)
    end
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_form.html.erb
<%= simple_form_for(@turn) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :hs %>
    <%= f.input :canceled %>
    <%= f.association :service %>
    <%= f.association :engineer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/turns/edit.html.erb
<h1>Editing Turn</h1>

<%= render 'form', turn: @turn %>

<%= link_to 'Show', @turn %> |
<%= link_to 'Back', turns_path %>

app/views/turns/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Asignar Disponibilidades', turns_search_turn_path %>

<table class="table caption-top">
    <caption>Listado de Turnos asignados</caption>
  <thead>
    <tr>
      <th>Date</th>
      <th>Hs</th>
      <th>Service</th>
      <th>Engineer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turns.each do |turn| %>
      <tr>
        <td><%= turn.date.strftime("%d-%m-%Y") %></td>
        <td><%= turn.hs.strftime("%H:%M") %></td>
        <td><%= turn.service.name %></td>
        <td><%= turn.engineer.name %></td>
        <td><%= link_to 'Show', turn %></td>
        <td><%= link_to 'Edit', edit_turn_path(turn) %></td>
        <td><%= link_to 'Destroy', turn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/turns/new.html.erb
<h1>New Turn</h1>

<%= render 'form', turn: @turn %>

<%= link_to 'Back', turns_path %>

app/views/turns/result_search.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Asignar turnos disponibles', new_turn_url(:date_from => @date_from, :date_to => @date_to, :service => @service), :style=>"font-weight:bold"%>


<table class="table caption-top">
  <caption>Listado de Turnos disponibles para asignar.</caption>
  <thead>
    <tr>
      <th>Date</th>
      <th>Hs</th>
      <th>Service</th>
      <th>Engineer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turns.each do |turn| %>
      <tr>
        <td><%= turn.date.strftime("%d-%m-%Y") %></td>
        <td><%= turn.hs.strftime("%H:%M") %></td>
        <td><%= turn.service.name %></td>
        <td><%= turn.engineer.name %></td>
        <td><%= link_to 'Show', turn %></td>
        <td><%= link_to 'Edit', edit_turn_path(turn) %></td>
        <td><%= link_to 'Destroy', turn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/turns/search_turn.html.erb
<form method="get" action="<%= turns_result_search_path %>" style="padding: 5%">
    <div class="mb-3">
        <label for="inputPassword3" class="form-label">Fecha desde:</label>
        <div class="col-md-12">
            <input class="form-control" name="date_from" id="date_from" type="date" value="<%= Date.today %>" min="<%= Date.today %>">
        </div><br>
        <label for="inputPassword3" class="form-label">Fecha hasta:</label>
        <div class="col-md-12">
            <input class="form-control" name="date_to" id="date_to" type="date" value="<%= Date.today %>" min="<%= Date.today %>">
        </div>
    </div>
    <div class="mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Servicio:</label>
        <div class="col-sm-12">
            <select name="service" id="service" class="form-control">
                <% @service.each do |service| %>
                    <option value="<%= "#{service.id}" %>"><%= service.name %></option>
                <% end %>
            </select>
        </div>
    </div>
    <input type="submit" onclick="" value="Buscar" class="btn btn-primary pull-right">
</form>

app/views/turns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @turn.date %>
</p>

<p>
  <strong>Hs:</strong>
  <%= @turn.hs %>
</p>

<p>
  <strong>Canceled:</strong>
  <%= @turn.canceled %>
</p>

<p>
  <strong>Service:</strong>
  <%= @turn.service_id %>
</p>

<p>
  <strong>Engineer:</strong>
  <%= @turn.engineer_id %>
</p>

<%= link_to 'Edit', edit_turn_path(@turn) %> |
<%= link_to 'Back', turns_path %>