config/routes.rb
Rails.application.routes.draw do
  
  get 'availabilities/search_availability', to: 'availabilities#search_availability'
  get 'availabilities/result_search', to: 'availabilities#result_search'

  get 'turns/search_turn', to: 'turns#search_turn'
  get 'turns/result_search', to: 'turns#result_search'

  resources :availability_engineers
  resources :turns
  resources :availabilities
  resources :calendars
  resources :services
  resources :engineers
  resources :schedules
  root 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :service
  belongs_to :engineer

  # Selecciono los turnos ocupados de un prestador en la fecha seleccionada.
  def self.turns_occupied(service, date_from, engineer)
    Availability.where('service_id = ? AND date = ? AND engineer_id = ? AND canceled = ?', service, date_from, engineer, "false").pluck(:hs)
  end

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: %i[ show edit update destroy ]

  # GET /availabilities or /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1 or /availabilities/1.json
  def show
  end

  # GET /availabilities/new
  def new
    #@availability = Availability.new
    @date_from = params[:date_from]
    @date_to = params[:date_to]

    @user_id = params[:engineer_id]
    @engineer = Engineer.find_by(user_id: @user_id)
    @service = params[:service_id]
    @date_from = params[:fecha]
    @hs = params[:hs]
    
      @turn = Availability.new(:date => @date_from, :hs => @hs, :canceled => false, :service_id => @service, :engineer_id => @engineer.id)
      #UserMailer.with(turn: @turn).turn_summary_email.deliver_now #if Rails.env.production?
      @turn.save!
      @turn_existe = Availability.where(:date => @date_from, :hs => @hs, :canceled => false, :service_id => @service).first
      #inserto tmbien en esta tabla para poder contar distintos
      if @turn_existe
        @abailability_engineer = AvailabilityEngineer.new(:availability_id => @turn_existe.id, :engineer_id => @engineer.id)
        @abailability_engineer.save!
      else
        @abailability_engineer = AvailabilityEngineer.new(:availability_id => @turn.id, :engineer_id => @engineer.id)
        @abailability_engineer.save!
      end

       if @turn.save
          flash[:notice] = "Turno registrado con éxito!"
          redirect_back(fallback_location: root_path)
        else
          flash[:error] = "Error en el registro del turno!"
          redirect_to :back
        end   
  end

  # GET /availabilities/1/edit
  def edit
  end

  # POST /availabilities or /availabilities.json
  def create
   
  end

  # PATCH/PUT /availabilities/1 or /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to availability_url(@availability), notice: "Availability was successfully updated." }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1 or /availabilities/1.json
  def destroy
    @availability.destroy

    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: "Availability was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search_availability
    @service = Service.all
  end

  def result_search
    @service = params[:service]
    @date_from = params[:date_from]
    @date_to = params[:date_to]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def availability_params
      params.require(:availability).permit(:date, :hs, :canceled, :service_id, :engineer_id)
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<%= form_with(model: availability) do |form| %>
  <% if availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
        <% availability.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :hs %>
    <%= form.time_select :hs %>
  </div>

  <div class="field">
    <%= form.label :canceled %>
    <%= form.check_box :canceled %>
  </div>

  <div class="field">
    <%= form.label :service_id %>
    <%= form.text_field :service_id %>
  </div>

  <div class="field">
    <%= form.label :engineer_id %>
    <%= form.text_field :engineer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<h1>Editing Availability</h1>

<%= render 'form', availability: @availability %>

<%= link_to 'Show', @availability %> |
<%= link_to 'Back', availabilities_path %>

app/views/availabilities/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Cargar disponibilidad', availabilities_search_availability_path %>

<table class="table caption-top">
  <caption>Listado de disponibilidad</caption>
  <thead>
    <tr>
      <th>Date</th>
      <th>Hs</th>
      <th>Canceled</th>
      <th>Service</th>
      <th>Engineer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= availability.date %></td>
        <td><%= availability.hs %></td>
        <td><%= availability.canceled %></td>
        <td><%= availability.service_id %></td>
        <td><%= availability.engineer_id %></td>
        <td><%= link_to 'Show', availability %></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
        <td><%= link_to 'Destroy', availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/availabilities/new.html.erb
<h1>New Availability</h1>

<%= render 'form', availability: @availability %>

<%= link_to 'Back', availabilities_path %>

app/views/availabilities/result_search.html.erb
<h4>Seleccione turnos disponibles para trabajar.</h4><br>

<% while (@date_from.to_date <= @date_to.to_date) %>

  <% @day = Date.parse(@date_from.to_s).strftime("%u") %>
  <% @turns_availables = Calendar.turns_availables(@service,@day,@date_from,@date_to) %>
  <% #byebug %>
  <% if @turns_availables.present? %>

    <div class="card" style="margin-bottom: 1%">
      <div class="card-header">
          <h5><b>Turnos disponibles para el día:</b>
            <%= Date.parse(@date_from.to_s).strftime("%d-%m-%Y") %>
            <b>| Servicio:</b> <%= @turns_availables.first.service.name %>
          </h5>
       </div>
    <div class="card-body">
    <p class="card-text">
        <% if @turns_availables.present? %>
        <h5>
            <span style="color: #428bca">█</span> Turno libre | <span style="color: red">█</span> Turno seleccionado
        </h5>
        <!-- Uso el each sobre 'turns_availables' para traer los valores del select realizado en el controlador y se lo asigno a variables-->
        <% cant = @turns_availables.count %>
        <% x=0 %>
        <% while (x < cant) %>
        	<% #byebug %>
            <% @turns_availables.each do |prueba| %>
            	<% #byebug %>
                <% @hs_start = prueba.schedule.hs_start %>
                <% link_to @hs_start.strftime("%H:%M") , new_calendar_path, data: { confirm: "Seguro?" }%>
                <% @hs_end = prueba.schedule.hs_end %>
                <% @duration_turn = prueba.duration_turn %>

                <!-- creo el link con la hora de inicio de atencion y luego sumo a la hora de inicio de atencion la duracion del turno, mientras la hora de inicio de atencion sea menor a la hora de final de atencion del prestador -->
                <% if @hs_end == 'Sat, 01 Jan 2000 00:00:00.000000000 UTC +00:00' %>
                	<% @hs_end = 'Sat, 01 Jan 2000 24:00:00.000000000 UTC +00:00' %>
                <% end %>
                <% while (@hs_start < @hs_end) do %>
                 <!-- por cada iteracion verifico si en el array existe el horario hs_start para determinar si lo creo como link (libre) o no (ocupado) -->
                 	<% @engineer = Engineer.find_by(user_id: current_user.id) %>
                    <% if Availability.turns_occupied(@service, @date_from, @engineer.id).include?(@hs_start) %>
                        <label style="font-size:30px; color:red">
                        <%= @hs_start.strftime("%H:%M") %></label><label style="font-size:30px"> | </label>
                        
                    <% else %>
                    	<label class="category-select">
                    		<%check_box_tag @hs_start.strftime("%H:%M"), @hs_start.strftime("%H:%M"), false %>
							<% @hs_start.strftime("%H:%M") %>                        	
                    	</label>
                      
                        <%= link_to @hs_start.strftime("%H:%M"), new_availability_url(:service_id => @service, :engineer_id => current_user, :hs => @hs_start, :fecha => @date_from, :date_from => @date_from, :date_to => @date_to), :style=>"font-size: 30px; font-weight:bold"%> <label style="font-size:30px"> | </label>

                    <% end %>
                    <%  @hs_start = @hs_start + @duration_turn.hour.hours + @duration_turn.min.minutes + @duration_turn.strftime('%S').to_i %>
                <%end%>
                <% x +=1 %>
                <hr />
            <% end %>
        <%end%>
        <% else %>
        <% end %>
    </p>
  </div>
</div>
    <% @date_from = @date_from.to_date + 1.day %>
<% else %>
    <% @date_from = @date_from.to_date + 1.day %>
<% end %>
<% end %>

app/views/availabilities/search_availability.html.erb
<form method="get" action="<%= availabilities_result_search_path %>" style="padding: 5%">
    <div class="mb-3">
        <label for="inputPassword3" class="col-md-2 col-form-label">Fecha desde:</label>
        <div class="col-md-12">
            <input class="form-control" name="date_from" id="date_from" type="date" value="<%= Date.today %>" min="<%= Date.today %>">
        </div>
        <label for="inputPassword3" class="col-md-2 col-form-label">Fecha hasta:</label>
        <div class="col-md-12">
            <input class="form-control" name="date_to" id="date_to" type="date" value="<%= Date.today %>" min="<%= Date.today %>">
        </div>
    </div>
    <div class="mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Servicio:</label>
        <div class="col-sm-12">
            <select name="service" id="service" class="form-control">
            <% @service.each do |service| %>
                <option value="<%= "#{service.id}" %>"><%= service.name %> - <%= service.id %></option>
            <% end %>
            </select>
        </div>
    </div>

    <div class="mb-3">
        <div class="col-sm-12">
            <input type="submit" onclick="" value="Buscar" class="btn btn-primary pull-right">
        </div>
    </div>
</form>
<hr />

app/views/availabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @availability.date %>
</p>

<p>
  <strong>Hs:</strong>
  <%= @availability.hs %>
</p>

<p>
  <strong>Canceled:</strong>
  <%= @availability.canceled %>
</p>

<p>
  <strong>Service:</strong>
  <%= @availability.service_id %>
</p>

<p>
  <strong>Engineer:</strong>
  <%= @availability.engineer_id %>
</p>

<%= link_to 'Edit', edit_availability_path(@availability) %> |
<%= link_to 'Back', availabilities_path %>