config/routes.rb
Rails.application.routes.draw do
  
  get 'availabilities/search_availability', to: 'availabilities#search_availability'
  get 'availabilities/result_search', to: 'availabilities#result_search'

  get 'turns/search_turn', to: 'turns#search_turn'
  get 'turns/result_search', to: 'turns#result_search'

  resources :availability_engineers
  resources :turns
  resources :availabilities
  resources :calendars
  resources :services
  resources :engineers
  resources :schedules
  root 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MaaS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if current_user %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user.admin? %>
        <li class="nav-item">
          <%= link_to 'Turnos', turns_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cronogramas', schedules_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Agendas', calendars_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Servicios', services_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Ingenieros', engineers_path, class: "dropdown-item" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Cargar Disponibilidad', availabilities_path, class: "dropdown-item" %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><%= current_user.email %></a>
      </form>
      <form class="d-flex">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-success" %>
      </form>
    </div>
    <% else %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="d-flex">
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-success" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-success" %>
      </form>
    </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>rails-n-bootstrap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    </head>

  <body>
    <header>
        <%= render 'layouts/navbar' %>
      </header>
    <%= yield %>
  </body>
</html>